### ISSUE TITLE
mmcv as part of mmpycocotools

### ISSUE THREAD

**Issue by megbalk** [agporto/Steginator#5]
@agporto It seems mmpycocotools is no longer supported. I read [here](https://github.com/open-mmlab/mmocr/issues/81) to instead install mmdet, but it still fails to load / find mmcv. I also tried installing pycocotools (as suggested [here](https://github.com/open-mmlab/mmdetection/issues/4987)) but it still can't find mmcv. Any ideas of how to fix it?

**Comment by agporto** [comment]
@megbalk Did you follow the regular install protocol?
`pip3 install openmim
mim install mmcv-full==1.4.0`

That should take care of installing mmcv
And yes, you can remove mmpycocotools from the list of requirements and use pycocotools instead.
I am closing this for now, but if you still have issues please reopen with error log.

**Comment by agporto** [comment]
@megbalk add line break between pip install openmim and min install mmcv-full==1.4.0

**Comment by megbalk** [comment]
@agporto it had an issue with openmim, and errored on "subprocess-exited-with-error" and thatn setup.py egg_info did not run successfully. I am unsure how to trouble shoot.

**Comment by agporto** [comment]
@megbalk if you still have it, please copy the entire error log. subprocess exited with error doesn't let me track down the problem. It is too generic

**Comment by megbalk** [comment]
```
voje-lab@voje-lab:~/Documents/GitHub/bryozoa/Steginator-magnifica$ pip3 install openmim mim
Defaulting to user installation because normal site-packages is not writeable
Collecting openmim
  Using cached openmim-0.3.9-py2.py3-none-any.whl (52 kB)
Collecting mim
  Using cached mim-0.2.43.tar.gz (38 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-nh19so3g/mim_29b6a09b51954a23bdfeb69b212e80f7/setup.py", line 43, in <module>
          import ConfigParser
      ModuleNotFoundError: No module named 'ConfigParser'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by agporto** [comment]
@megbalk they are separate lines. Please refer to the installation instructions in the main repo.
First line: pip install openmim
Second line: mim install mmcv-full==1.4.0

**Comment by megbalk** [comment]
@agporto I didn't realize that I needed to rerun all the beginning code - oops!
I am not re-cloning Steginator, though, correct?

I have the following error after running `pip3 install e.` (after running everything above):
`(steginator) voje-lab@voje-lab:~/Documents/GitHub/bryozoa/Steginator-magnifica$ pip3 install -e .
Obtaining file:///home/voje-lab/Documents/GitHub/bryozoa/Steginator-magnifica
  Preparing metadata (setup.py) ... done
Requirement already satisfied: matplotlib in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from mmdet==2.11.0) (3.5.3)
Collecting mmpycocotools
  Using cached mmpycocotools-12.0.3.tar.gz (23 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from mmdet==2.11.0) (1.21.5)
Requirement already satisfied: six in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from mmdet==2.11.0) (1.16.0)
Requirement already satisfied: terminaltables in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from mmdet==2.11.0) (3.1.10)
Requirement already satisfied: timm in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from mmdet==2.11.0) (0.9.10)
Requirement already satisfied: opencv-python in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from mmdet==2.11.0) (4.8.1.78)
Requirement already satisfied: pandas in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from mmdet==2.11.0) (1.3.5)
Collecting streamlit
  Using cached streamlit-1.23.1-py2.py3-none-any.whl (8.9 MB)
Collecting streamlit-drawable-canvas
  Using cached streamlit_drawable_canvas-0.9.3-py3-none-any.whl (1.2 MB)
Requirement already satisfied: pillow in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from mmdet==2.11.0) (9.4.0)
Requirement already satisfied: pycocotools in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from mmdet==2.11.0) (2.0.7)
Requirement already satisfied: xgboost==1.5.2 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from mmdet==2.11.0) (1.5.2)
Requirement already satisfied: scikit-learn in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from mmdet==2.11.0) (1.0.2)
Requirement already satisfied: scipy in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from xgboost==1.5.2->mmdet==2.11.0) (1.7.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from matplotlib->mmdet==2.11.0) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from matplotlib->mmdet==2.11.0) (23.2)
Requirement already satisfied: pyparsing>=2.2.1 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from matplotlib->mmdet==2.11.0) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from matplotlib->mmdet==2.11.0) (2.8.2)
Requirement already satisfied: cycler>=0.10 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from matplotlib->mmdet==2.11.0) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from matplotlib->mmdet==2.11.0) (4.38.0)
Requirement already satisfied: setuptools>=18.0 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from mmpycocotools->mmdet==2.11.0) (60.2.0)
Requirement already satisfied: cython>=0.27.3 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from mmpycocotools->mmdet==2.11.0) (3.0.5)
Requirement already satisfied: pytz>=2017.3 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from pandas->mmdet==2.11.0) (2023.3.post1)
Requirement already satisfied: joblib>=0.11 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from scikit-learn->mmdet==2.11.0) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from scikit-learn->mmdet==2.11.0) (3.1.0)
Requirement already satisfied: click<9,>=7.0 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from streamlit->mmdet==2.11.0) (8.1.7)
Requirement already satisfied: pympler<2,>=0.9 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from streamlit->mmdet==2.11.0) (1.0.1)
Requirement already satisfied: importlib-metadata<7,>=1.4 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from streamlit->mmdet==2.11.0) (6.7.0)
Requirement already satisfied: toml<2 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from streamlit->mmdet==2.11.0) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.0.1 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from streamlit->mmdet==2.11.0) (4.7.1)
Requirement already satisfied: blinker<2,>=1.0.0 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from streamlit->mmdet==2.11.0) (1.6.3)
Requirement already satisfied: pyarrow>=4.0 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from streamlit->mmdet==2.11.0) (12.0.1)
Requirement already satisfied: rich<14,>=10.11.0 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from streamlit->mmdet==2.11.0) (13.6.0)
Requirement already satisfied: protobuf<5,>=3.20 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from streamlit->mmdet==2.11.0) (4.24.4)
Collecting gitpython!=3.1.19,<4,>=3
  Using cached GitPython-3.1.40-py3-none-any.whl (190 kB)
Requirement already satisfied: validators<1,>=0.2 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from streamlit->mmdet==2.11.0) (0.20.0)
Requirement already satisfied: tzlocal<5,>=1.1 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from streamlit->mmdet==2.11.0) (4.3.1)
Requirement already satisfied: cachetools<6,>=4.0 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from streamlit->mmdet==2.11.0) (5.3.2)
Requirement already satisfied: requests<3,>=2.4 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from streamlit->mmdet==2.11.0) (2.28.2)
Requirement already satisfied: pydeck<1,>=0.1.dev5 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from streamlit->mmdet==2.11.0) (0.8.1b0)
Collecting altair<6,>=4.0
  Using cached altair-5.0.1-py3-none-any.whl (471 kB)
Requirement already satisfied: watchdog in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from streamlit->mmdet==2.11.0) (3.0.0)
Requirement already satisfied: tenacity<9,>=8.0.0 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from streamlit->mmdet==2.11.0) (8.2.3)
Requirement already satisfied: tornado<7,>=6.0.3 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from streamlit->mmdet==2.11.0) (6.2)
Requirement already satisfied: huggingface-hub in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from timm->mmdet==2.11.0) (0.16.4)
Requirement already satisfied: safetensors in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from timm->mmdet==2.11.0) (0.4.0)
Requirement already satisfied: torchvision in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from timm->mmdet==2.11.0) (0.11.0)
Requirement already satisfied: pyyaml in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from timm->mmdet==2.11.0) (6.0.1)
Requirement already satisfied: torch>=1.7 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from timm->mmdet==2.11.0) (1.10.0)
Collecting jsonschema>=3.0
  Using cached jsonschema-4.17.3-py3-none-any.whl (90 kB)
Requirement already satisfied: toolz in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from altair<6,>=4.0->streamlit->mmdet==2.11.0) (0.12.0)
Requirement already satisfied: jinja2 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from altair<6,>=4.0->streamlit->mmdet==2.11.0) (3.1.2)
Requirement already satisfied: gitdb<5,>=4.0.1 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from gitpython!=3.1.19,<4,>=3->streamlit->mmdet==2.11.0) (4.0.11)
Requirement already satisfied: zipp>=0.5 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from importlib-metadata<7,>=1.4->streamlit->mmdet==2.11.0) (3.15.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from requests<3,>=2.4->streamlit->mmdet==2.11.0) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from requests<3,>=2.4->streamlit->mmdet==2.11.0) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from requests<3,>=2.4->streamlit->mmdet==2.11.0) (1.26.18)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from requests<3,>=2.4->streamlit->mmdet==2.11.0) (3.3.2)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from rich<14,>=10.11.0->streamlit->mmdet==2.11.0) (2.16.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from rich<14,>=10.11.0->streamlit->mmdet==2.11.0) (2.2.0)
Requirement already satisfied: backports.zoneinfo in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from tzlocal<5,>=1.1->streamlit->mmdet==2.11.0) (0.2.1)
Requirement already satisfied: pytz-deprecation-shim in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from tzlocal<5,>=1.1->streamlit->mmdet==2.11.0) (0.1.0.post0)
Requirement already satisfied: decorator>=3.4.0 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from validators<1,>=0.2->streamlit->mmdet==2.11.0) (5.1.1)
Requirement already satisfied: fsspec in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from huggingface-hub->timm->mmdet==2.11.0) (2023.1.0)
Requirement already satisfied: filelock in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from huggingface-hub->timm->mmdet==2.11.0) (3.12.2)
Requirement already satisfied: tqdm>=4.42.1 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from huggingface-hub->timm->mmdet==2.11.0) (4.65.2)
Requirement already satisfied: smmap<6,>=3.0.1 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3->streamlit->mmdet==2.11.0) (5.0.1)
Requirement already satisfied: MarkupSafe>=2.0 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from jinja2->altair<6,>=4.0->streamlit->mmdet==2.11.0) (2.1.3)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit->mmdet==2.11.0) (0.19.3)
Requirement already satisfied: importlib-resources>=1.4.0 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit->mmdet==2.11.0) (5.12.0)
Requirement already satisfied: attrs>=17.4.0 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit->mmdet==2.11.0) (23.1.0)
Requirement already satisfied: pkgutil-resolve-name>=1.3.10 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit->mmdet==2.11.0) (1.3.10)
Requirement already satisfied: mdurl~=0.1 in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from markdown-it-py>=2.2.0->rich<14,>=10.11.0->streamlit->mmdet==2.11.0) (0.1.2)
Requirement already satisfied: tzdata in /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages (from pytz-deprecation-shim->tzlocal<5,>=1.1->streamlit->mmdet==2.11.0) (2023.3)
Building wheels for collected packages: mmpycocotools
  Building wheel for mmpycocotools (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.7
      creating build/lib.linux-x86_64-3.7/pycocotools
      copying pycocotools/__init__.py -> build/lib.linux-x86_64-3.7/pycocotools
      copying pycocotools/coco.py -> build/lib.linux-x86_64-3.7/pycocotools
      copying pycocotools/mask.py -> build/lib.linux-x86_64-3.7/pycocotools
      copying pycocotools/cocoeval.py -> build/lib.linux-x86_64-3.7/pycocotools
      running build_ext
      Compiling pycocotools/_mask.pyx because it changed.
      [1/1] Cythonizing pycocotools/_mask.pyx
      /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-op07u49j/mmpycocotools_33f26bd026ce4bb9a3cabdcb042e513b/pycocotools/_mask.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      creating build/common
      creating build/temp.linux-x86_64-3.7
      creating build/temp.linux-x86_64-3.7/common
      creating build/temp.linux-x86_64-3.7/pycocotools
      gcc -pthread -B /home/voje-lab/miniconda3/envs/steginator/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages/numpy/core/include -Icommon -I/home/voje-lab/miniconda3/envs/steginator/include/python3.7m -c ../common/maskApi.c -o build/temp.linux-x86_64-3.7/../common/maskApi.o
      cc1: fatal error: ../common/maskApi.c: No such file or directory
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mmpycocotools
  Running setup.py clean for mmpycocotools
Failed to build mmpycocotools
Installing collected packages: gitpython, mmpycocotools, jsonschema, altair, streamlit, streamlit-drawable-canvas, mmdet
  Running setup.py install for mmpycocotools ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for mmpycocotools did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      running install
      /home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        setuptools.SetuptoolsDeprecationWarning,
      running build
      running build_py
      creating build/lib.linux-x86_64-3.7
      creating build/lib.linux-x86_64-3.7/pycocotools
      copying pycocotools/__init__.py -> build/lib.linux-x86_64-3.7/pycocotools
      copying pycocotools/coco.py -> build/lib.linux-x86_64-3.7/pycocotools
      copying pycocotools/mask.py -> build/lib.linux-x86_64-3.7/pycocotools
      copying pycocotools/cocoeval.py -> build/lib.linux-x86_64-3.7/pycocotools
      running build_ext
      creating build/temp.linux-x86_64-3.7
      creating build/temp.linux-x86_64-3.7/common
      creating build/temp.linux-x86_64-3.7/pycocotools
      gcc -pthread -B /home/voje-lab/miniconda3/envs/steginator/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/voje-lab/miniconda3/envs/steginator/lib/python3.7/site-packages/numpy/core/include -Icommon -I/home/voje-lab/miniconda3/envs/steginator/include/python3.7m -c ../common/maskApi.c -o build/temp.linux-x86_64-3.7/../common/maskApi.o
      cc1: fatal error: ../common/maskApi.c: No such file or directory
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> mmpycocotools

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
`

**Comment by agporto** [comment]
No need to reclone. The error message is again the mmpycocotools failed installation. Just remove that package from requirements/runtime.txt and repeat.

**Comment by megbalk** [comment]
Thanks! I got it working! I had to reinstall dlib too, and am unsure why.
